version: 2
updates:
- package-ecosystem: "maven"
  directory: "/processor"
  schedule:
    interval: "monthly"
  groups:
    processor-production-dependencies:
      dependency-type: "production"
      update-types: 
      - "major"
      - "minor"

- package-ecosystem: "maven"
  directory: "/dashboard"
  schedule:
    interval: "monthly"
  groups:
    dashboard-production-dependencies:
      dependency-type: "production"
      update-types:
      - "major"
      - "minor"
